/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SmarakRouteImport } from './routes/smarak'
import { Route as NationalRouteImport } from './routes/national'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SmarakRoute = SmarakRouteImport.update({
  id: '/smarak',
  path: '/smarak',
  getParentRoute: () => rootRouteImport,
} as any)
const NationalRoute = NationalRouteImport.update({
  id: '/national',
  path: '/national',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experience': typeof ExperienceRoute
  '/national': typeof NationalRoute
  '/smarak': typeof SmarakRoute
  '/trust': typeof TrustRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experience': typeof ExperienceRoute
  '/national': typeof NationalRoute
  '/smarak': typeof SmarakRoute
  '/trust': typeof TrustRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/experience': typeof ExperienceRoute
  '/national': typeof NationalRoute
  '/smarak': typeof SmarakRoute
  '/trust': typeof TrustRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/experience' | '/national' | '/smarak' | '/trust'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/experience' | '/national' | '/smarak' | '/trust'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/experience'
    | '/national'
    | '/smarak'
    | '/trust'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExperienceRoute: typeof ExperienceRoute
  NationalRoute: typeof NationalRoute
  SmarakRoute: typeof SmarakRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smarak': {
      id: '/smarak'
      path: '/smarak'
      fullPath: '/smarak'
      preLoaderRoute: typeof SmarakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/national': {
      id: '/national'
      path: '/national'
      fullPath: '/national'
      preLoaderRoute: typeof NationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExperienceRoute: ExperienceRoute,
  NationalRoute: NationalRoute,
  SmarakRoute: SmarakRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
